const Carddata = [
    {
        imgsrc: "https://media.istockphoto.com/photos/flying-color-books-on-pastel-yellow-background-picture-id1304915362?s=612x612",
        productTitle: "First",
        afterTitle: "one",
        productDetails: "nvjhdbvkdsgvdbvrgfhvdbgschgdujkdbkjcvgdvdhvcydghcdshvbcdgvicdhci",
        price: "800",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/alarm-clock-and-color-books-on-pastel-yellow-background-picture-id1304915230?s=612x612",
        productTitle: "Second",
        afterTitle: "two",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "900",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/credit-cards-and-smartphone-for-online-payment-for-goods-and-services-picture-id1272591540?s=612x612",
        productTitle: "Third",
        afterTitle: "three",
        productDetails: "nvjhdbvkdsgvdbvrgfhvdbgschgdujkdbkjcvgdvdhvcydghcdshvbcdgvicdhci",
        price: "1000",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/books-colorful-business-concept-line-icon-reading-sign-in-flat-linear-vector-id1317565498?s=612x612",
        productTitle: "Fourth",
        afterTitle: "four",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "1100",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/red-notepad-on-a-yellow-background-for-decoration-for-text-design-for-picture-id1148250433?s=612x612",
        productTitle: "Fifth",
        afterTitle: "five",
        productDetails: "nvjhdbvkdsgvdbvrgfhvdbgschgdujkdbkjcvgdvdhvcydghcdshvbcdgvicdhci",
        price: "1200",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "Sixth",
        afterTitle: "six",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "1300",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "Seven",
        afterTitle: "seven",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "1400",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "eight",
        afterTitle: "eight",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "1500",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "nine",
        afterTitle: "nine",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "1600",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "ten",
        afterTitle: "ten",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "1700",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/flying-color-books-on-pastel-yellow-background-picture-id1304915362?s=612x612",
        productTitle: "eleven",
        afterTitle: "eleven",
        productDetails: "nvjhdbvkdsgvdbvrgfhvdbgschgdujkdbkjcvgdvdhvcydghcdshvbcdgvicdhci",
        price: "1800",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/alarm-clock-and-color-books-on-pastel-yellow-background-picture-id1304915230?s=612x612",
        productTitle: "twell",
        afterTitle: "twell",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "1900",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/credit-cards-and-smartphone-for-online-payment-for-goods-and-services-picture-id1272591540?s=612x612",
        productTitle: "Thirteen",
        afterTitle: "thirteen",
        productDetails: "nvjhdbvkdsgvdbvrgfhvdbgschgdujkdbkjcvgdvdhvcydghcdshvbcdgvicdhci",
        price: "2000",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/books-colorful-business-concept-line-icon-reading-sign-in-flat-linear-vector-id1317565498?s=612x612",
        productTitle: "Fourteen",
        afterTitle: "fourteen",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "2100",
    },
    {
        imgsrc: "https://media.istockphoto.com/photos/red-notepad-on-a-yellow-background-for-decoration-for-text-design-for-picture-id1148250433?s=612x612",
        productTitle: "Fifteen",
        afterTitle: "fifteen",
        productDetails: "nvjhdbvkdsgvdbvrgfhvdbgschgdujkdbkjcvgdvdhvcydghcdshvbcdgvicdhci",
        price: "2200",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "Sixteen",
        afterTitle: "sixteen",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "2300",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "Seventeen",
        afterTitle: "seventeen",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "2400",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "eighteen",
        afterTitle: "eighteen",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "2500",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "nineteen",
        afterTitle: "nineteen",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "2600",
    },
    {
        imgsrc: "https://media.istockphoto.com/vectors/colorful-floor-discotheque-logo-design-template-colorful-floor-icon-vector-id1307673617",
        productTitle: "twenty",
        afterTitle: "twenty",
        productDetails: "vchndjvhcjdkbvdhvkjdbhvgdhbvhdgvbhdbvdhgbvhbryvgbhdbkvbdskcbdvhfb",
        price: "2700",
    }
]


export default Carddata;